---
## more info https://github.com/crazy-max/ghaction-github-labeler
- name: "automerge :bell:"
  color: "8f4fbc"
  description: ""
- name: "bot :robot:"
  color: "69cde9"
  description: ""
- name: "bug :bug:"
  color: "b60205"
  description: ""
- name: "dependencies :game_die:"
  color: "0366d6"
  description: ""
- name: "docker :whale:"
  color: "0366d6"
  description: ""
- name: "documentation :memo:"
  color: "c5def5"
  description: ""
- name: "duplicate :busts_in_silhouette:"
  color: "cccccc"
  description: ""
- name: "enhancement :sparkles:"
  color: "0054ca"
  description: ""
- name: "feature request :bulb:"
  color: "0e8a16"
  description: ""
- name: "feedback :mega:"
  color: "03a9f4"
  description: ""
- name: "future maybe :rocket:"
  color: "fef2c0"
  description: ""
- name: "github-actions :octocat:"
  color: "43e5d0"
  description: ""
- name: "good first issue :hatching_chick:"
  color: "7057ff"
  description: ""
- name: "help wanted :pray:"
  color: "4caf50"
  description: ""
- name: "invalid :no_entry_sign:"
  color: "e6e6e6"
  description: ""
- name: "investigate :mag:"
  color: "e6625b"
  description: ""
- name: "javascript :coffee:"
  color: "e69c4e"
  description: ""
- name: "needs more info :thinking:"
  color: "795548"
  description: ""
- name: "pinned :pushpin:"
  color: "28008e"
  description: ""
- name: "python :snake:"
  color: "52dda7"
  description: ""
- name: "question :question:"
  color: "3f51b5"
  description: ""
- name: "regression :boom:"
  color: "cd8703"
  description: ""
- name: "sponsor :sparkling_heart:"
  color: "fedbf0"
  description: ""
- name: "stale :skull:"
  color: "237da0"
  description: ""
- name: "upstream :eyes:"
  color: "fbca04"
  description: ""
- name: "wontfix :coffin:"
  color: "ffffff"
  description: ""
