---
name: Build with reusable workflows

on:
  # push:
  #   branches:
  #     - "**"
  # pull_request:
  workflow_dispatch:
    inputs:
      dispatch-tag:
        description: "Tag to apply to pushed images"
        required: true
        default: "dispatch"

permissions:
  actions: read
  contents: read

jobs:
  config:
    name: "Config"
    uses: ./.github/workflows/_config.yml

  metadata:
    name: "Metadata"
    needs: [config]
    uses: felddy/reusable-workflows/.github/workflows/docker-metadata.yml@develop
    with:
      image_name: ${{ needs.config.outputs.image_name }}

  build-each-platform:
    name: "Build platform"
    needs:
      - config
      - metadata
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        platform: ${{ fromJson(needs.config.outputs.platforms_json) }}
    uses: felddy/reusable-workflows/.github/workflows/docker-build-image.yml@develop
    with:
      artifact_name: ${{ needs.config.outputs.image_archive_artifact_name }}
      cache_from_scopes: ${{ matrix.platform }}
      cache_to_scope: ${{ matrix.platform }}
      image_labels: ${{ needs.metadata.outputs.image_labels }}
      image_archive_name_stem: ${{ matrix.platform }}
      platforms: ${{ matrix.platform }}
