---
name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
  schedule:
    - cron: "20 10 * * *" # everyday at 10:20 UTC
  workflow_dispatch:

permissions:
  actions: read
  contents: read

env:
  QEMU_STRACE: "true"

jobs:
  diagnostics:
    name: "Diagnostics"
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@df4d23a4977438215339cf0fafceda8d9af8a0e5 # tag=v4.0.0
        with:
          overall_threshold: major
          packages_threshold: major_outage

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@5355a8e5e6ac5a302e746a1c4b7747a0393863c8 # tag=v2.3.0

  build-image-alpine:
    name: "Alpine"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/ppc64le
          - linux/s390x
        base_tag:
          - 18-alpine3.20
          - 20-alpine3.20
          - 22-alpine3.20
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag=v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # tag=v3.1.0
        with:
          image: tonistiigi/binfmt:master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@aa33708b10e362ff993539393ff100fa93ed6a27 # tag=v3.5.0

      - name: Build image
        uses: docker/build-push-action@1ca370b3a9802c92e886402e0dd88098a2533b12 # tag=v6.4.1
        with:
          build-args: BASE_TAG=${{ matrix.base_tag }}
          context: .
          file: ./Dockerfile-alpine
          outputs: type=docker,dest=/tmp/image.tar
          platforms: ${{ matrix.platform }}
          push: false

  build-image-debian:
    name: "Debian"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          # - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/ppc64le
          - linux/s390x
        base_tag:
          - 18-bookworm-slim
          - 20-bookworm-slim
          - 22-bookworm-slim
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag=v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # tag=v3.1.0
        with:
          image: tonistiigi/binfmt:master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@aa33708b10e362ff993539393ff100fa93ed6a27 # tag=v3.5.0

      - name: Build image
        uses: docker/build-push-action@1ca370b3a9802c92e886402e0dd88098a2533b12 # tag=v6.4.1
        with:
          build-args: BASE_TAG=${{ matrix.base_tag }}
          context: .
          file: ./Dockerfile-debian
          outputs: type=docker,dest=/tmp/image.tar
          platforms: ${{ matrix.platform }}
          push: false
